In [5]:
import urllib.request
import pandas as pd

In [2]:
url = 'https://www.data.go.kr/dataset/fileDownload.do?atchFileId=FILE_000000001420522&fileDetailSn=1&publicDataDetailPk=uddi:2b432a68-9f06-47d5-a749-bacf219266a6_201712281438'

In [6]:
data = pd.read_csv(url, encoding = 'ms949')

In [7]:
data

,연도,월,서울특별시건수,서울특별시보증잔액(원),부산광역시건수,부산광역시보증잔액(원),대구광역시건수,대구광역시보증잔액(원),인천광역시건수,인천광역시보증잔액(원),...,경상남도건수,경상남도보증잔액(원),강원도 건수,강원도 보증잔액(원),제주도건수,제주도보증잔액(원),세종특별자치시건수,세종특별자치시보증잔액(원),기타공급건수,기타공급금액(원)
0,2004,4,"99,409","1,487,147,563,206","38,847","680,823,453,048","22,555","288,902,567,319","91,914","1,505,212,647,687",...,"32,059","383,912,930,127","10,575","119,438,366,616","3,161","27,926,477,853",NaN,NaN,555,"5,531,901,068"
1,2004,5,"96,670","1,448,694,063,819","37,736","657,355,201,838","21,962","279,660,451,110","90,898","1,487,740,661,641",...,"31,497","379,959,796,333","10,275","114,779,805,965","2,968","25,772,900,897",NaN,NaN,530,"5,281,905,651"
2,2004,6,"93,682","1,405,068,946,075","36,594","634,189,207,015","21,532","277,004,076,536","89,606","1,465,787,109,986",...,"30,817","376,015,742,137","9,866","111,427,790,961","2,823","24,414,727,514",NaN,NaN,482,"5,018,362,912"
3,2004,7,"90,871","1,356,839,443,201","35,586","614,058,735,338","21,059","273,235,430,176","88,550","1,448,986,404,560",...,"30,153","367,610,546,236","9,656","109,832,649,576","2,772","23,797,111,539",NaN,NaN,462,"4,918,233,114"
4,2004,8,"88,428","1,321,409,572,877","34,639","596,540,424,000","20,665","270,110,772,554","87,209","1,418,985,476,272",...,"29,551","362,574,568,960","9,456","108,856,539,276","2,705","22,582,898,249",NaN,NaN,453,"4,796,327,060"
5,2004,9,"85,824","1,286,053,127,622","33,843","585,772,056,922","20,120","261,755,054,291","85,047","1,359,963,688,289",...,"29,008","359,401,598,473","9,112","106,463,523,040","2,662","22,032,712,826",NaN,NaN,438,"4,641,597,917"
6,2004,10,"82,472","1,241,532,634,847","32,749","565,199,083,133","19,614","256,077,762,237","83,398","1,322,616,334,076",...,"28,421","354,958,055,468","8,532","87,419,461,000","2,591","21,589,467,953",NaN,NaN,422,"4,404,907,563"
7,2004,11,"79,076","1,196,442,985,444","31,430","542,166,896,902","18,951","249,062,527,669","80,279","1,253,706,189,611",...,"27,599","346,861,220,174","8,077","81,392,074,483","2,510","20,768,061,432",NaN,NaN,408,"4,290,687,721"
8,2004,12,"76,845","1,156,711,040,571","30,615","529,053,890,128","18,552","244,880,302,008","79,522","1,238,081,860,531",...,"27,023","346,034,669,264","7,788","78,838,104,648","2,387","19,757,667,537",NaN,NaN,395,"4,193,561,260"
9,2005,1,"75,158","1,124,989,582,775","29,965","519,210,551,185","18,105","238,919,730,092","78,852","1,226,742,362,823",...,"26,476","338,438,412,269","7,550","76,070,718,286","2,279","18,852,459,827",NaN,NaN,381,"4,046,372,326"
10,2005,2,"73,394","1,097,892,065,822","29,328","509,720,040,505","17,746","234,058,232,840","78,234","1,213,893,364,590",...,"25,840","328,208,597,648","7,312","73,677,168,352","2,182","18,208,324,590",NaN,NaN,365,"3,883,998,065"
11,2005,3,"70,696","1,060,988,760,769","28,307","488,318,713,330","17,056","226,055,542,479","76,443","1,175,329,814,912",...,"25,193","321,147,808,485","7,047","70,454,995,721","2,102","17,492,575,898",NaN,NaN,380,"4,108,812,969"
12,2005,4,"68,239","1,026,197,746,407","27,372","470,409,534,517","16,412","216,254,816,549","74,716","1,135,804,144,076",...,"24,629","315,429,389,682","6,800","66,173,355,795","2,050","17,000,587,595",NaN,NaN,404,"4,491,942,081"
13,2005,5,"65,630","990,423,446,257","26,151","438,657,110,546","15,758","206,631,865,364","72,830","1,089,541,867,295",...,"23,924","316,255,831,139","6,532","62,565,242,443","2,028","18,454,195,559",NaN,NaN,425,"4,842,236,642"
14,2005,6,"62,748","952,701,892,682","24,614","400,989,794,142","15,238","201,355,472,561","69,012","1,012,523,248,719",...,"22,878","300,572,320,333","6,240","60,183,195,232","1,911","17,881,733,681",NaN,NaN,426,"4,934,190,513"
15,2005,7,"61,444","930,320,624,047","23,983","384,969,381,879","14,826","193,269,681,515","68,094","988,351,742,223",...,"22,247","280,609,903,931","6,078","58,305,174,271","1,867","17,390,399,668",NaN,NaN,417,"4,844,893,188"
16,2005,8,"59,882","896,808,116,283","23,444","375,285,508,003","14,501","191,429,311,031","67,209","968,940,269,149",...,"21,457","257,191,759,498","5,910","55,526,046,995","1,835","17,200,796,919",NaN,NaN,411,"4,796,118,647"
17,2005,9,"58,305","871,085,700,672","22,740","354,797,208,309","14,131","184,927,775,587","64,974","929,167,000,057",...,"20,922","246,717,955,645","5,789","61,536,661,461","1,807","16,819,453,826",NaN,NaN,421,"5,127,468,158"
18,2005,10,"56,719","851,423,814,686","22,192","348,710,798,711","13,630","177,173,924,061","63,990","914,622,468,524",...,"20,178","230,187,357,551","5,603","59,735,411,605","1,778","16,296,063,289",NaN,NaN,429,"5,340,852,746"
19,2005,11,"55,311","826,346,907,949","21,500","331,054,964,297","13,183","173,453,063,841","62,915","895,347,039,272",...,"19,675","221,911,218,272","5,379","56,433,163,477","1,733","15,687,963,348",NaN,NaN,434,"5,461,513,623"
20,2005,12,"54,031","805,125,873,562","20,901","321,758,544,070","12,677","170,252,975,865","61,920","876,887,090,696",...,"19,085","209,449,369,243","5,215","54,664,768,022","1,686","15,200,882,759",NaN,NaN,429,"5,417,780,738"
21,2006,1,"52,907","781,619,102,979","20,433","313,852,281,243","12,408","180,855,716,941","60,683","855,087,784,076",...,"18,660","201,613,512,515","5,083","53,099,485,360","1,635","14,543,072,294",NaN,NaN,415,"5,298,478,605"
22,2006,2,"51,958","765,776,468,992","19,857","301,710,649,028","12,063","175,938,111,629","59,779","837,976,268,892",...,"18,237","196,147,558,193","4,970","51,979,889,853","1,535","13,333,500,659",NaN,NaN,407,"5,263,541,571"
23,2006,3,"50,712","744,788,589,361","19,135","284,808,738,809","11,632","170,629,870,324","58,334","811,348,424,524",...,"17,629","186,165,003,941","4,866","51,732,061,297","1,480","12,326,745,031",NaN,NaN,406,"5,295,791,165"
24,2006,4,"49,538","727,099,374,831","18,603","272,571,032,728","11,257","167,999,378,353","57,188","791,430,929,413",...,"17,239","180,175,466,619","4,725","50,139,561,167","1,433","11,824,352,850",NaN,NaN,398,"5,180,119,451"
25,2006,5,"48,344","715,844,170,532","17,963","257,283,419,329","10,942","163,789,281,722","55,527","762,649,730,870",...,"16,808","175,523,078,539","4,633","49,259,548,601","1,413","11,658,945,451",NaN,NaN,395,"5,205,845,693"
26,2006,6,"47,197","700,316,597,634","17,279","242,074,315,797","10,581","159,584,607,046","53,411","722,943,612,194",...,"16,193","169,195,225,830","4,531","49,123,114,485","1,382","11,370,638,088",NaN,NaN,393,"5,319,088,821"
27,2006,7,"46,332","686,700,806,480","16,912","232,648,000,191","10,405","161,757,074,344","52,720","711,673,451,069",...,"15,830","165,100,863,344","4,559","54,273,336,692","1,359","11,056,447,973",NaN,NaN,393,"5,456,525,479"
28,2006,8,"45,472","672,594,574,433","16,531","225,660,557,605","10,486","174,784,019,947","52,141","701,741,664,052",...,"15,523","163,606,712,740","4,526","58,820,560,012","1,336","10,816,600,587",NaN,NaN,383,"5,369,543,603"
29,2006,9,"44,516","659,669,134,835","16,168","216,532,444,111","10,225","173,383,984,330","50,762","676,566,666,620",...,"15,161","160,240,830,762","4,443","62,582,721,981","1,308","10,564,822,035",NaN,NaN,378,"5,412,913,125"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,2015,6,"145,289","6,796,070,000,000","17,873","1,535,090,000,000","9,740","608,877,000,000","53,835","2,771,780,000,000",...,"20,943","1,889,580,000,000","5,171","276,694,000,000","1,393","138,617,000,000","7,215","680,415,000,000",89,"2,372,539,094"
135,2015,7,"147,660","6,915,710,000,000","18,189","1,575,190,000,000","9,764","617,990,000,000","53,942","2,728,560,000,000",...,"20,993","1,898,460,000,000","4,923","241,704,000,000","1,391","139,096,000,000","7,244","679,627,000,000",89,"2,372,066,761"
136,2015,8,"150,033","7,036,730,000,000","17,720","1,511,770,000,000","9,804","621,360,000,000","53,890","2,607,830,000,000",...,"21,979","2,072,360,000,000","4,865","233,579,000,000","1,546","141,498,000,000","7,195","665,041,000,000",88,"2,304,493,022"
137,2015,9,"152,652","7,180,380,000,000","18,514","1,655,020,000,000","9,489","614,759,000,000","54,059","2,597,300,000,000",...,"22,151","2,069,690,000,000","4,929","235,729,000,000","1,644","142,581,000,000","7,096","650,729,000,000",86,"2,248,874,022"
138,2015,10,"155,681","7,366,350,000,000","18,765","1,686,040,000,000","9,556","617,892,000,000","54,122","2,561,940,000,000",...,"24,310","2,366,590,000,000","6,062","362,733,000,000","1,645","142,874,000,000","6,682","583,198,000,000",85,"2,218,617,087"
139,2015,11,"157,043","7,488,020,000,000","18,485","1,635,930,000,000","9,806","623,741,000,000","53,981","2,586,730,000,000",...,"24,276","2,367,740,000,000","6,363","400,986,000,000","1,646","143,035,000,000","9,397","1,068,740,000,000",83,"2,133,562,620"
140,2015,12,"157,914","7,569,300,000,000","18,233","1,587,740,000,000","10,447","659,775,000,000","54,116","2,619,230,000,000",...,"25,841","2,585,750,000,000","6,419","405,042,000,000","1,655","143,994,000,000","9,724","1,081,360,000,000",82,"2,091,569,540"
141,2016,1,"158,031","7,588,160,000,000","18,190","1,583,210,000,000","11,104","789,775,000,000","54,180","2,640,560,000,000",...,"25,822","2,589,770,000,000","6,016","373,409,000,000","1,658","144,380,000,000","10,325","1,188,890,000,000",81,"2,083,136,018"
142,2016,2,"158,922","7,652,580,000,000","18,229","1,585,550,000,000","10,877","782,479,000,000","54,148","2,648,390,000,000",...,"25,828","2,587,290,000,000","6,035","373,669,000,000","1,669","145,691,000,000","10,572","1,246,960,000,000",80,"2,077,637,671"
143,2016,3,"160,182","7,709,560,000,000","18,449","1,579,590,000,000","11,185","821,980,000,000","54,479","2,664,890,000,000",...,"25,191","2,496,290,000,000","6,089","375,369,000,000","1,682","146,735,000,000","10,744","1,324,830,000,000",79,"2,068,049,843"
144,2016,4,"162,021","7,839,000,000,000","19,662","1,750,470,000,000","11,772","885,087,000,000","55,848","2,823,300,000,000",...,"25,764","2,536,610,000,000","6,140","377,663,000,000","1,689","147,052,000,000","10,342","1,302,300,000,000",77,"2,040,129,485"
145,2016,5,"163,645","7,962,040,000,000","19,965","1,753,160,000,000","11,899","884,018,000,000","56,386","2,856,720,000,000",...,"25,562","2,560,580,000,000","6,207","379,876,000,000","1,717","151,950,000,000","9,843","1,283,160,000,000",75,"1,994,407,684"
146,2016,6,"165,140","8,089,250,000,000","20,373","1,776,410,000,000","11,862","845,212,000,000","56,816","2,877,250,000,000",...,"26,891","2,720,950,000,000","7,208","490,145,000,000","1,917","166,873,000,000","9,060","1,260,730,000,000",77,"2,091,095,739"
147,2016,7,"166,540","8,204,480,000,000","21,393","1,943,580,000,000","12,009","808,447,000,000","56,692","2,828,130,000,000",...,"27,030","2,729,360,000,000","7,768","549,088,000,000","1,963","167,692,000,000","9,791","1,428,930,000,000",78,"2,127,508,032"
148,2016,8,"168,505","8,369,020,000,000","21,591","1,929,740,000,000","13,276","987,687,000,000","57,125","2,826,770,000,000",...,"28,788","2,947,940,000,000","8,042","562,351,000,000","2,035","170,883,000,000","9,841","1,431,800,000,000",79,"2,170,998,401"
149,2016,9,"170,372","8,525,190,000,000","21,713","1,920,500,000,000","13,731","1,046,740,000,000","57,403","2,839,210,000,000",...,"29,087","2,960,840,000,000","8,188","566,778,000,000","2,077","172,470,000,000","10,973","1,457,960,000,000",80,"2,197,998,413"
150,2016,10,"172,144","8,684,136,957,489","22,057","1,930,602,479,866","14,608","1,197,735,026,890","57,904","2,872,785,215,326",...,"30,048","3,087,176,224,769","8,248","568,250,501,175","2,116","175,683,761,011","11,387","1,494,319,385,911",78,"2,136,105,626"
151,2016,11,"174,291","8,833,496,228,451","23,880","2,108,648,991,872","15,200","1,210,542,008,517","58,842","2,909,929,686,524",...,"33,452","3,620,186,909,243","8,089","546,851,916,726","1,993","144,787,863,346","11,264","1,465,239,381,368",81,"2,216,626,800"
152,2016,12,"175,791","8,935,387,228,089","24,692","2,111,607,101,952","15,805","1,231,027,593,455","59,728","2,940,977,093,947",...,"34,028","3,613,883,156,532","8,946","652,204,230,232","1,851","113,933,920,251","12,050","1,611,469,830,038",83,"2,303,080,800"
153,2017,1,"175,777","8,941,621,503,449","25,689","2,243,708,944,143","16,220","1,250,873,672,292","59,950","2,944,006,295,191",...,"34,169","3,595,381,871,004","9,019","651,864,103,800","1,765","89,029,127,032","12,077","1,612,543,961,207",83,"2,302,116,358"
154,2017,2,"176,664","9,018,184,069,075","26,520","2,348,002,954,084","16,744","1,280,918,380,565","60,993","3,128,961,961,578",...,"35,876","3,796,571,086,266","9,783","733,520,809,788","1,742","75,488,815,842","12,031","1,599,280,677,586",83,"2,301,630,783"
155,2017,3,"177,578","9,083,638,791,372","26,788","2,315,555,831,089","17,198","1,285,999,026,399","61,045","3,065,823,967,770",...,"36,693","3,815,662,866,291","10,234","773,744,160,177","1,810","75,912,636,344","11,502","1,500,180,489,834",82,"2,232,274,853"
156,2017,4,"178,884","9,176,446,172,437","27,169","2,307,633,837,394","17,552","1,297,375,000,173","61,258","3,033,278,110,916",...,"37,097","3,798,633,260,459","10,341","776,753,801,399","1,872","77,550,980,186","11,510","1,484,747,193,468",82,"2,232,274,853"
157,2017,5,"179,889","9,242,114,498,206","28,659","2,513,370,233,822","17,809","1,299,593,044,170","61,570","3,026,311,802,093",...,"37,533","3,786,000,839,763","10,436","778,956,206,859","1,919","79,293,498,459","13,405","1,757,416,927,684",82,"2,225,596,911"
158,2017,6,"181,264","9,339,050,938,661","30,390","2,736,357,638,065","17,665","1,243,858,316,740","61,861","2,980,197,754,977",...,"37,290","3,671,902,147,805","10,591","784,604,535,752","1,949","80,799,039,207","14,757","1,937,498,651,373",82,"2,223,519,891"
159,2017,7,"182,090","9,419,652,489,593","29,818","2,580,670,713,122","17,766","1,236,228,944,264","61,830","2,925,765,606,297",...,"38,225","3,780,353,478,234","10,815","820,569,034,686","1,971","82,138,357,613","14,796","1,939,651,296,376",82,"2,223,028,383"
160,2017,8,"183,321","9,520,761,599,037","29,893","2,515,351,192,713","17,435","1,157,600,010,549","62,331","2,924,351,988,046",...,"38,269","3,737,052,650,783","10,907","823,548,514,279","1,994","83,104,396,671","14,757","1,932,264,100,961",81,"2,199,635,482"
161,2017,9,"184,718","9,660,043,073,447","30,389","2,522,624,809,571","17,456","1,119,969,937,452","64,698","3,327,670,191,058",...,"39,337","3,836,391,494,168","10,949","826,399,875,304","2,042","86,249,510,629","14,692","1,911,840,749,742",79,"2,184,243,371"
162,2017,10,"185,916","9,784,079,929,078","31,780","2,652,418,581,046","17,578","1,095,347,232,990","64,837","3,263,084,614,698",...,"39,502","3,820,860,662,016","10,982","827,012,707,032","2,066","87,278,617,134","13,977","1,855,367,357,272",78,"2,165,453,375"
163,2017,11,"187,388","9,936,073,660,849","33,048","2,780,811,117,231","17,780","1,085,361,096,218","64,649","3,104,460,716,769",...,"41,509","4,093,010,061,295","10,933","789,459,563,645","2,116","89,702,874,324","13,685","1,792,332,663,765",77,"2,131,756,272"

In [8]:
data.to_csv('개인보증 은행계정 주택소재지별 잔액현황.csv')