In [1]:
import pandas as pd
import requests
from pandas.io.json import json_normalize

url = 'http://kosis.kr/openapi/statisticsData.do?method=getList&apiKey=Mzg4M2JhYWQ2NTRhYzNmNTFlZDI1MzdjYzlkODcwMjg=&format=json&jsonVD=Y&userStatsId=kinatic/116/DT_MLTM_5416/2/1/20190418171726&prdSe=Y&newEstPrdCnt=1'

response = requests.get(url)

json = response.json()

df = json_normalize(json)

In [2]:
df

,C1,C1_NM,C1_OBJ_NM,C1_OBJ_NM_ENG,DT,ITM_ID,ITM_NM,ITM_NM_ENG,ORG_ID,PRD_DE,PRD_SE,TBL_ID,TBL_NM,UNIT_NM,UNIT_NM_ENG
0,13102883384A.01,전국,구분,Classification,117730,13103883384T1,계,Total,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
1,13102883384A.01,전국,구분,Classification,52323,13103883384T2,단독,Single house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
2,13102883384A.01,전국,구분,Classification,26723,13103883384T3,다가구,Multihouseholds,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
3,13102883384A.01,전국,구분,Classification,5017,13103883384T4,연립,Row house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
4,13102883384A.01,전국,구분,Classification,8159,13103883384T5,다세대,Multifamily housing,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
5,13102883384A.01,전국,구분,Classification,25508,13103883384T6,아파트,Apartment,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
6,13102883384A.02,수도권,구분,Classification,69808,13103883384T1,계,Total,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
7,13102883384A.02,수도권,구분,Classification,18354,13103883384T2,단독,Single house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
8,13102883384A.02,수도권,구분,Classification,19026,13103883384T3,다가구,Multihouseholds,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
9,13102883384A.02,수도권,구분,Classification,4107,13103883384T4,연립,Row house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
10,13102883384A.02,수도권,구분,Classification,6901,13103883384T5,다세대,Multifamily housing,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
11,13102883384A.02,수도권,구분,Classification,21420,13103883384T6,아파트,Apartment,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
12,13102883384A.03,지방,구분,Classification,47922,13103883384T1,계,Total,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
13,13102883384A.03,지방,구분,Classification,33969,13103883384T2,단독,Single house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
14,13102883384A.03,지방,구분,Classification,7697,13103883384T3,다가구,Multihouseholds,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
15,13102883384A.03,지방,구분,Classification,910,13103883384T4,연립,Row house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
16,13102883384A.03,지방,구분,Classification,1258,13103883384T5,다세대,Multifamily housing,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
17,13102883384A.03,지방,구분,Classification,4088,13103883384T6,아파트,Apartment,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
18,13102883384A.04,서울,구분,Classification,47534,13103883384T1,계,Total,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
19,13102883384A.04,서울,구분,Classification,11042,13103883384T2,단독,Single house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
20,13102883384A.04,서울,구분,Classification,13514,13103883384T3,다가구,Multihouseholds,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
21,13102883384A.04,서울,구분,Classification,3007,13103883384T4,연립,Row house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
22,13102883384A.04,서울,구분,Classification,5233,13103883384T5,다세대,Multifamily housing,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
23,13102883384A.04,서울,구분,Classification,14738,13103883384T6,아파트,Apartment,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
24,13102883384A.05,부산,구분,Classification,7857,13103883384T1,계,Total,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
25,13102883384A.05,부산,구분,Classification,4510,13103883384T2,단독,Single house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
26,13102883384A.05,부산,구분,Classification,2142,13103883384T3,다가구,Multihouseholds,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
27,13102883384A.05,부산,구분,Classification,111,13103883384T4,연립,Row house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
28,13102883384A.05,부산,구분,Classification,633,13103883384T5,다세대,Multifamily housing,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
29,13102883384A.05,부산,구분,Classification,461,13103883384T6,아파트,Apartment,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,13102883384A.16,전북,구분,Classification,2765,13103883384T1,계,Total,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
91,13102883384A.16,전북,구분,Classification,2463,13103883384T2,단독,Single house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
92,13102883384A.16,전북,구분,Classification,185,13103883384T3,다가구,Multihouseholds,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
93,13102883384A.16,전북,구분,Classification,113,13103883384T4,연립,Row house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
94,13102883384A.16,전북,구분,Classification,4,13103883384T5,다세대,Multifamily housing,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
95,13102883384A.16,전북,구분,Classification,0,13103883384T6,아파트,Apartment,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
96,13102883384A.17,전남,구분,Classification,3408,13103883384T1,계,Total,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
97,13102883384A.17,전남,구분,Classification,3358,13103883384T2,단독,Single house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
98,13102883384A.17,전남,구분,Classification,42,13103883384T3,다가구,Multihouseholds,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
99,13102883384A.17,전남,구분,Classification,4,13103883384T4,연립,Row house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
100,13102883384A.17,전남,구분,Classification,4,13103883384T5,다세대,Multifamily housing,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
101,13102883384A.17,전남,구분,Classification,0,13103883384T6,아파트,Apartment,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
102,13102883384A.18,경북,구분,Classification,6894,13103883384T1,계,Total,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
103,13102883384A.18,경북,구분,Classification,4894,13103883384T2,단독,Single house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
104,13102883384A.18,경북,구분,Classification,717,13103883384T3,다가구,Multihouseholds,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
105,13102883384A.18,경북,구분,Classification,10,13103883384T4,연립,Row house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
106,13102883384A.18,경북,구분,Classification,8,13103883384T5,다세대,Multifamily housing,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
107,13102883384A.18,경북,구분,Classification,1265,13103883384T6,아파트,Apartment,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
108,13102883384A.19,경남,구분,Classification,6109,13103883384T1,계,Total,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
109,13102883384A.19,경남,구분,Classification,4938,13103883384T2,단독,Single house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
110,13102883384A.19,경남,구분,Classification,438,13103883384T3,다가구,Multihouseholds,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
111,13102883384A.19,경남,구분,Classification,58,13103883384T4,연립,Row house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
112,13102883384A.19,경남,구분,Classification,47,13103883384T5,다세대,Multifamily housing,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
113,13102883384A.19,경남,구분,Classification,628,13103883384T6,아파트,Apartment,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
114,13102883384A.20,제주,구분,Classification,1189,13103883384T1,계,Total,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
115,13102883384A.20,제주,구분,Classification,1049,13103883384T2,단독,Single house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
116,13102883384A.20,제주,구분,Classification,45,13103883384T3,다가구,Multihouseholds,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
117,13102883384A.20,제주,구분,Classification,67,13103883384T4,연립,Row house,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
118,13102883384A.20,제주,구분,Classification,28,13103883384T5,다세대,Multifamily housing,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit
119,13102883384A.20,제주,구분,Classification,0,13103883384T6,아파트,Apartment,116,2017,A,DT_MLTM_5416,주택 멸실현황,호,Apartment Unit

In [3]:
df.to_csv('./주택 멸실현황.csv', encoding='ms949')