In [1]:
import pandas as pd
import requests
from pandas.io.json import json_normalize

In [2]:
# 데이터 접속 주소 입력
url = 'http://kosis.kr/openapi/statisticsData.do?method=getList&apiKey=NmE2ZTYwYzZjNzUxNjdiZjRiOTkxNDI4MWQ4MzhmYWQ=&format=json&jsonVD=Y&userStatsId=akwkhh/101/DT_1OH0409/2/1/20190418180114&prdSe=Y&newEstPrdCnt=1'
# 정상 여부 확인 (200 정상)
response = requests.get(url)
response
# JSON 데이터 획득
json = response.json()
# PandasDataframe변환
df = json_normalize(json)
df.head()

,C1,C1_NM,C1_NM_ENG,C1_OBJ_NM,C2,C2_NM,C2_OBJ_NM,DT,ITM_ID,ITM_NM,ORG_ID,PRD_DE,PRD_SE,TBL_ID,TBL_NM,UNIT_NM,UNIT_NM_ENG
0,00,전국,Whole country,거주지역별,000,총계,소유지분별,11000007,T001,일반가구수,101,2017,A,DT_1OH0409,거주지역별 주택소유지분별 주택소유 가구수 현황,가구,Households
1,00,전국,Whole country,거주지역별,010,1호이하,소유지분별,8038349,T001,일반가구수,101,2017,A,DT_1OH0409,거주지역별 주택소유지분별 주택소유 가구수 현황,가구,Households
2,00,전국,Whole country,거주지역별,020,1호초과~2호이하,소유지분별,2202298,T001,일반가구수,101,2017,A,DT_1OH0409,거주지역별 주택소유지분별 주택소유 가구수 현황,가구,Households
3,00,전국,Whole country,거주지역별,030,2호초과~3호이하,소유지분별,499920,T001,일반가구수,101,2017,A,DT_1OH0409,거주지역별 주택소유지분별 주택소유 가구수 현황,가구,Households
4,00,전국,Whole country,거주지역별,040,3호초과,소유지분별,259440,T001,일반가구수,101,2017,A,DT_1OH0409,거주지역별 주택소유지분별 주택소유 가구수 현황,가구,Households

In [3]:
df.to_csv("./178_거주지역별 주택소유지분별 주택소유 가구수 현황.csv", encoding = "ms949")