In [4]:
import pandas as pd
import requests
from pandas.io.json import json_normalize

url = 'http://kosis.kr/openapi/statisticsData.do?method=getList&apiKey=Mzg4M2JhYWQ2NTRhYzNmNTFlZDI1MzdjYzlkODcwMjg=&format=json&jsonVD=Y&userStatsId=kinatic/101/DT_1OH0502/2/1/20190418172230&prdSe=Y&newEstPrdCnt=1'

response = requests.get(url)

json = response.json()

df = json_normalize(json)

In [5]:
df

,C1,C1_NM,C1_OBJ_NM,C2,C2_NM,C2_OBJ_NM,DT,ITM_ID,ITM_NM,ORG_ID,PRD_DE,PRD_SE,TBL_ID,TBL_NM,UNIT_NM,UNIT_NM_ENG
0,000,주택,주택형태별,00,총계,주택소유자수별,14963975,T001,주택수,101,2017,A,DT_1OH0502,주택소유자수별 주택수 현황(단독 및 공동 소유),호,Households
1,000,주택,주택형태별,01,1인,주택소유자수별,13216748,T001,주택수,101,2017,A,DT_1OH0502,주택소유자수별 주택수 현황(단독 및 공동 소유),호,Households
2,000,주택,주택형태별,02,2인,주택소유자수별,1571006,T001,주택수,101,2017,A,DT_1OH0502,주택소유자수별 주택수 현황(단독 및 공동 소유),호,Households
3,000,주택,주택형태별,03,3인,주택소유자수별,108598,T001,주택수,101,2017,A,DT_1OH0502,주택소유자수별 주택수 현황(단독 및 공동 소유),호,Households
4,000,주택,주택형태별,04,4인,주택소유자수별,31579,T001,주택수,101,2017,A,DT_1OH0502,주택소유자수별 주택수 현황(단독 및 공동 소유),호,Households
5,000,주택,주택형태별,05,5인이상,주택소유자수별,36044,T001,주택수,101,2017,A,DT_1OH0502,주택소유자수별 주택수 현황(단독 및 공동 소유),호,Households
6,010,아파트,주택형태별,00,총계,주택소유자수별,8697344,T001,주택수,101,2017,A,DT_1OH0502,주택소유자수별 주택수 현황(단독 및 공동 소유),호,Households
7,010,아파트,주택형태별,01,1인,주택소유자수별,7645409,T001,주택수,101,2017,A,DT_1OH0502,주택소유자수별 주택수 현황(단독 및 공동 소유),호,Households
8,010,아파트,주택형태별,02,2인,주택소유자수별,1003927,T001,주택수,101,2017,A,DT_1OH0502,주택소유자수별 주택수 현황(단독 및 공동 소유),호,Households
9,010,아파트,주택형태별,03,3인,주택소유자수별,38418,T001,주택수,101,2017,A,DT_1OH0502,주택소유자수별 주택수 현황(단독 및 공동 소유),호,Households
10,010,아파트,주택형태별,04,4인,주택소유자수별,6305,T001,주택수,101,2017,A,DT_1OH0502,주택소유자수별 주택수 현황(단독 및 공동 소유),호,Households
11,010,아파트,주택형태별,05,5인이상,주택소유자수별,3285,T001,주택수,101,2017,A,DT_1OH0502,주택소유자수별 주택수 현황(단독 및 공동 소유),호,Households

In [6]:
df.to_csv('./주택소유자수별 주택수 현황(단독 및 공동 소유).csv', encoding='ms949')