In [1]:
import pandas as pd
import requests
from pandas.io.json import json_normalize

In [3]:
url='http://kosis.kr/openapi/statisticsData.do?method=getList&apiKey=ZmY2Yzg3OTY1ODQ3Y2FlMDE4MDVkZTMyN2MxM2ZjMjA=&format=json&jsonVD=Y&userStatsId=botopia/116/TX_116110033/2/1/20190418174023&prdSe=Y&newEstPrdCnt=1'
response = requests.get(url)
response

In [4]:
json = response.json()

In [5]:
df = json_normalize(json)
df.head()

,C1,C1_NM,C1_NM_ENG,C1_OBJ_NM,C1_OBJ_NM_ENG,C2,C2_NM,C2_NM_ENG,C2_OBJ_NM,DT,ITM_ID,ITM_NM,ORG_ID,PRD_DE,PRD_SE,TBL_ID,TBL_NM,UNIT_NM,UNIT_NM_ENG
0,1511613102251771A.00,계,Total,시도별,Metropolitan city and province,1511613102251771B.0,계,Total,용도별,6460489,1611613103251771T2,동수,116,2007,A,TX_116110033,건축물 현황(시도별용도별),동,Building
1,1511613102251771A.00,계,Total,시도별,Metropolitan city and province,1511613102251771B.2,주거용,NaN,용도별,4364730,1611613103251771T2,동수,116,2007,A,TX_116110033,건축물 현황(시도별용도별),동,Building
2,1511613102251771A.00,계,Total,시도별,Metropolitan city and province,1511613102251771B.3,상업용,NaN,용도별,1010972,1611613103251771T2,동수,116,2007,A,TX_116110033,건축물 현황(시도별용도별),동,Building
3,1511613102251771A.00,계,Total,시도별,Metropolitan city and province,1511613102251771B.4,공업용,NaN,용도별,215591,1611613103251771T2,동수,116,2007,A,TX_116110033,건축물 현황(시도별용도별),동,Building
4,1511613102251771A.00,계,Total,시도별,Metropolitan city and province,1511613102251771B.5,문교사회용,NaN,용도별,163355,1611613103251771T2,동수,116,2007,A,TX_116110033,건축물 현황(시도별용도별),동,Building

In [6]:
df.to_csv("./건축물 현황(시도별,용도별).csv")